# Generated by Django 6.1 on 2026-08-08 07:56

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('route_short_name', models.CharField(blank=True, max_length=32)),
                ('route_long_name', models.CharField(blank=True, max_length=255)),
                ('route_type', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('stop_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('stop_name', models.CharField(blank=True, max_length=255)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=7856)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('service_id', models.CharField(blank=True, max_length=64)),
                ('direction_id', models.SmallIntegerField(null=True)),
                ('shape_id', models.CharField(blank=True, max_length=64)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='reliability.route')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_sequence', models.IntegerField()),
                ('arrival_s', models.IntegerField(null=True)),
                ('departure_s', models.IntegerField(null=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='reliability.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='reliability.trip')),
            ],
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['route', 'direction_id'], name='reliability_route_i_801737_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['trip', 'stop_sequence'], name='reliability_trip_id_bd3bb6_idx'),
        ),
        migrations.AddIndex(
            model_name='stoptime',
            index=models.Index(fields=['stop'], name='reliability_stop_id_413e6c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stoptime',
            constraint=models.UniqueConstraint(fields=('trip', 'stop_sequence'), name='uniq_trip_stopsequence'),
        ),
    ]
