# Generated by Django 6.1 on 2026-08-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('polls', models.IntegerField(default=0)),
                ('observations', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
                ('last_feed_ts', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=64)),
                ('service_date', models.CharField(max_length=8)),
                ('stop_id', models.CharField(max_length=64)),
                ('stop_sequence', models.IntegerField()),
                ('route_id', models.CharField(blank=True, max_length=64)),
                ('vehicle_id', models.CharField(blank=True, max_length=64)),
                ('arrival_time', models.BigIntegerField(null=True)),
                ('arrival_delay', models.IntegerField(null=True)),
                ('departure_time', models.BigIntegerField(null=True)),
                ('departure_delay', models.IntegerField(null=True)),
                ('schedule_relationship', models.CharField(blank=True, max_length=16)),
                ('trip_relationship', models.CharField(blank=True, max_length=16)),
                ('feed_ts', models.BigIntegerField()),
                ('poll_count', models.IntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['route_id', 'stop_id'], name='reliability_route_i_b9adf9_idx'), models.Index(fields=['service_date'], name='reliability_service_5ae800_idx')],
                'constraints': [models.UniqueConstraint(fields=('trip_id', 'service_date', 'stop_id', 'stop_sequence'), name='uniq_observation')],
            },
        ),
    ]
