# Generated by Django 6.1 on 2026-08-08 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0002_harvestrun_observation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=64)),
                ('route_short_name', models.CharField(blank=True, max_length=32)),
                ('direction_id', models.SmallIntegerField(null=True)),
                ('is_peak', models.BooleanField()),
                ('observations', models.IntegerField()),
                ('n_on_time', models.IntegerField()),
                ('n_early', models.IntegerField()),
                ('n_late', models.IntegerField()),
                ('otp_pct', models.FloatField()),
                ('pct_early', models.FloatField()),
                ('pct_late', models.FloatField()),
                ('median_deviation_s', models.FloatField()),
                ('p90_deviation_s', models.FloatField()),
                ('worst_deviation_s', models.FloatField()),
                ('sufficient_sample', models.BooleanField()),
                ('window_start', models.CharField(max_length=8)),
                ('window_end', models.CharField(max_length=8)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance', to='reliability.stop')),
            ],
            options={
                'indexes': [models.Index(fields=['otp_pct'], name='reliability_otp_pct_09cf84_idx'), models.Index(fields=['route_short_name'], name='reliability_route_s_4bf462_idx')],
                'constraints': [models.UniqueConstraint(fields=('route_id', 'direction_id', 'stop', 'is_peak'), name='uniq_segment')],
            },
        ),
    ]
