# Generated by Django 6.1 on 2026-08-09 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0003_segmentperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polled_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('feed_ts', models.BigIntegerField(null=True)),
                ('rows', models.IntegerField(default=0)),
                ('ok', models.BooleanField(default=True)),
                ('error', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
