# Generated by Django 6.1 on 2026-08-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0004_poll'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentperformance',
            name='bunching_rate_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='excess_wait_time_s',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='gap_rate_pct',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='headway_observations',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='is_terminus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='mean_actual_headway_s',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='mean_scheduled_headway_s',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='segmentperformance',
            name='min_stop_sequence',
            field=models.IntegerField(null=True),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['route_id', 'stop_id', 'arrival_time'], name='reliability_route_i_30a402_idx'),
        ),
        migrations.AddIndex(
            model_name='segmentperformance',
            index=models.Index(fields=['excess_wait_time_s'], name='reliability_excess__83f841_idx'),
        ),
    ]
