# Generated by Django 6.1 on 2026-08-14 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reliability', '0005_segmentperformance_bunching_rate_pct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentperformance',
            name='headway_days',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='DailyHeadway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=64)),
                ('route_short_name', models.CharField(blank=True, max_length=32)),
                ('direction_id', models.SmallIntegerField(null=True)),
                ('is_peak', models.BooleanField()),
                ('service_date', models.CharField(db_index=True, max_length=8)),
                ('day_type', models.CharField(choices=[('weekday', 'Weekday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], db_index=True, max_length=8)),
                ('intervals', models.IntegerField()),
                ('mean_scheduled_headway_s', models.FloatField()),
                ('mean_actual_headway_s', models.FloatField()),
                ('excess_wait_time_s', models.FloatField()),
                ('bunching_rate_pct', models.FloatField()),
                ('gap_rate_pct', models.FloatField()),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_headways', to='reliability.stop')),
            ],
            options={
                'indexes': [models.Index(fields=['service_date', 'day_type'], name='reliability_service_d65537_idx'), models.Index(fields=['route_id', 'stop', 'service_date'], name='reliability_route_i_29dbb1_idx'), models.Index(fields=['excess_wait_time_s'], name='reliability_excess__8da4c9_idx')],
                'constraints': [models.UniqueConstraint(fields=('route_id', 'direction_id', 'stop', 'is_peak', 'service_date'), name='uniq_daily_headway')],
            },
        ),
    ]
